version: 2

sources:
  - name: gcs
    description: "Google Cloud Storage connector tables"
    tables:
      - name: test_results_data
        description: "Patient data from GCS connector"
        columns:
          - name: patient
            description: "Patient identifier"
          - name: date
            description: "Visit date"
          - name: age
            description: "Patient age"
          - name: sugar_level
            description: "Blood sugar level"

models:
  - name: stg_csv_data
    description: "Staging model for patient data processing from GCP bucket CSV"
    columns:
      - name: patient_id
        description: "Patient identifier"
        tests:
          - not_null
      - name: visit_date
        description: "Visit date"
        tests:
          - not_null
      - name: patient_age
        description: "Patient age in years"
        tests:
          - not_null
      - name: blood_sugar_level
        description: "Blood sugar level measurement"
        tests:
          - not_null
  
  - name: patient_analytics
    description: "Patient analytics mart with aggregated metrics"
    columns:
      - name: patient_id
        description: "Patient identifier"
        tests:
          - not_null
          - unique
      - name: total_visits
        description: "Total number of visits"
        tests:
          - not_null
      - name: avg_blood_sugar
        description: "Average blood sugar level"
        tests:
          - not_null